# Generated by Django 3.0.3 on 2020-03-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_api_key', models.CharField(max_length=300)),
                ('project_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('ifc_file', models.FileField(upload_to='project')),
            ],
        ),
    ]
